# Generated by Django 4.1.2 on 2022-12-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('A', 'Alinhamento'), ('AM', 'Arrumar o motor'), ('B', 'Balanceamento'), ('TPC', 'Troca de painel de combustível'), ('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('TP', 'Troca de pneu'), ('TF', 'Troca de farol'), ('TL', 'Troca de lanterna'), ('TPF', 'Troca de pastilhas do freio'), ('TFA', 'Troca de filtro de ar'), ('TFC', 'Troca de filtro de combustível'), ('TLI', 'Troca de lâmpadas internas')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocolo', models.CharField(blank=True, max_length=32, null=True)),
                ('CategoriaManutencao', models.ManyToManyField(to='servicos.categoriamanutencao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
